[package]
name = "uci"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.80"
chrono = "0.4.38"
dirs = "5.0.1"
engine = { path = "../engine" }
log = "0.4.21"
simplelog = "0.12.2"
statig = "0.3.0"
test-case = "3.3.1"
testresult = "0.4.0"
winnow = "0.6.5"
